//! L'archive culturelle affichée sur la page d'accueil : des répliques de
//! films et séries de science-fiction, tirées au sort côté client. Les
//! données vivent ici plutôt que dans le JavaScript, pour que la page ne
//! porte que la logique d'affichage — le contenu, lui, est servi par
//! l'API et pourrait un jour changer sans toucher au front-end.

use axum::Json;
use serde::Serialize;

#[derive(Serialize, Clone, Copy)]
pub struct Transmission {
    pub fr: &'static str,
    pub vo: &'static str,
    pub title: &'static str,
    pub creator: &'static str,
    pub year: u32,
    pub kind: &'static str,
}

const ARCHIVE: &[Transmission] = &[
    Transmission { fr: "Tous ces moments se perdront dans le temps, comme des larmes dans la pluie.",
        vo: "All those moments will be lost in time, like tears in rain.",
        title: "Blade Runner", creator: "Ridley Scott", year: 1982, kind: "Film" },
    Transmission { fr: "Je suis désolé, Dave. Je crains de ne pouvoir le faire.",
        vo: "I'm sorry, Dave. I'm afraid I can't do that.",
        title: "2001 : L'Odyssée de l'espace", creator: "Stanley Kubrick", year: 1968, kind: "Film" },
    Transmission { fr: "Dans l'espace, personne ne vous entend crier.",
        vo: "In space, no one can hear you scream.",
        title: "Alien", creator: "Ridley Scott", year: 1979, kind: "Film" },
    Transmission { fr: "Les grandes choses ont de petits commencements.",
        vo: "Big things have small beginnings.",
        title: "Prometheus", creator: "Ridley Scott", year: 2012, kind: "Film" },
    Transmission { fr: "La vérité est ailleurs.",
        vo: "The truth is out there.",
        title: "X-Files", creator: "Chris Carter", year: 1993, kind: "Série" },
    Transmission { fr: "L'espace, frontière de l'infini.",
        vo: "Space: the final frontier.",
        title: "Star Trek", creator: "Gene Roddenberry", year: 1966, kind: "Série" },
    Transmission { fr: "Il n'y a pas de cuillère.",
        vo: "There is no spoon.",
        title: "Matrix", creator: "Lana & Lilly Wachowski", year: 1999, kind: "Film" },
    Transmission { fr: "Ainsi parlons-nous tous.",
        vo: "So say we all.",
        title: "Battlestar Galactica", creator: "Ronald D. Moore", year: 2004, kind: "Série" },
    Transmission { fr: "Les portes et les angles, gamin. C'est là qu'ils t'auront.",
        vo: "Doors and corners, kid. That's where they get you.",
        title: "The Expanse", creator: "Mark Fergus & Hawk Ostby", year: 2015, kind: "Série" },
    Transmission { fr: "J'ai bien l'intention de mal me tenir.",
        vo: "I aim to misbehave.",
        title: "Serenity / Firefly", creator: "Joss Whedon", year: 2005, kind: "Film" },
    Transmission { fr: "La peur tue l'esprit.",
        vo: "Fear is the mind-killer.",
        title: "Dune", creator: "Denis Villeneuve — d'après Frank Herbert", year: 2021, kind: "Film" },
    Transmission { fr: "Mourir pour une juste cause est la chose la plus humaine qui soit.",
        vo: "Dying for the right cause is the most human thing we can do.",
        title: "Blade Runner 2049", creator: "Denis Villeneuve", year: 2017, kind: "Film" },
    Transmission { fr: "Si tu pouvais voir ta vie entière, changerais-tu quelque chose ?",
        vo: "If you could see your whole life, would you change things?",
        title: "Premier Contact", creator: "Denis Villeneuve", year: 2016, kind: "Film" },
    Transmission { fr: "Voulez-vous en savoir plus ?",
        vo: "Would you like to know more?",
        title: "Starship Troopers", creator: "Paul Verhoeven", year: 1997, kind: "Film" },
    Transmission { fr: "Mort ou vif, tu viens avec moi.",
        vo: "Dead or alive, you're coming with me.",
        title: "RoboCop", creator: "Paul Verhoeven", year: 1987, kind: "Film" },
    Transmission { fr: "Ramène tes fesses sur Mars.",
        vo: "Get your ass to Mars.",
        title: "Total Recall", creator: "Paul Verhoeven", year: 1990, kind: "Film" },
    Transmission { fr: "Viens avec moi si tu veux vivre.",
        vo: "Come with me if you want to live.",
        title: "Terminator", creator: "James Cameron", year: 1984, kind: "Film" },
    Transmission { fr: "Il n'y a pas d'autre destin que celui que l'on se forge.",
        vo: "There is no fate but what we make for ourselves.",
        title: "Terminator 2 : Le Jugement dernier", creator: "James Cameron", year: 1991, kind: "Film" },
    Transmission { fr: "C'est fini, mec. C'est fini !",
        vo: "Game over, man. Game over!",
        title: "Aliens, le retour", creator: "James Cameron", year: 1986, kind: "Film" },
    Transmission { fr: "Là où nous allons, nous n'aurons pas besoin d'yeux pour voir.",
        vo: "Where we're going, we won't need eyes to see.",
        title: "Event Horizon", creator: "Paul W. S. Anderson", year: 1997, kind: "Film" },
    Transmission { fr: "Autrefois, nous levions les yeux vers le ciel en rêvant de notre place parmi les étoiles.",
        vo: "We used to look up at the sky and wonder at our place in the stars.",
        title: "Interstellar", creator: "Christopher Nolan", year: 2014, kind: "Film" },
    Transmission { fr: "Ces plaisirs violents ont des fins violentes.",
        vo: "These violent delights have violent ends.",
        title: "Westworld", creator: "Jonathan Nolan & Lisa Joy", year: 2016, kind: "Série" },
    Transmission { fr: "Que la Force soit avec toi.",
        vo: "May the Force be with you.",
        title: "Star Wars", creator: "George Lucas", year: 1977, kind: "Film" },
    Transmission { fr: "Je brûle ma décence pour l'avenir d'un autre.",
        vo: "I burn my decency for someone else's future.",
        title: "Andor", creator: "Tony Gilroy", year: 2022, kind: "Série" },
    Transmission { fr: "C'est la voie.",
        vo: "This is the way.",
        title: "The Mandalorian", creator: "Jon Favreau", year: 2019, kind: "Série" },
    Transmission { fr: "À plus, cow-boy de l'espace.",
        vo: "See you, space cowboy.",
        title: "Cowboy Bebop", creator: "Shinichiro Watanabe", year: 1998, kind: "Série" },
    Transmission { fr: "Le réseau est vaste et infini.",
        vo: "The net is vast and infinite.",
        title: "Ghost in the Shell", creator: "Mamoru Oshii", year: 1995, kind: "Film" },
    Transmission { fr: "Neo-Tokyo est sur le point d'exploser.",
        vo: "Neo-Tokyo is about to explode.",
        title: "Akira", creator: "Katsuhiro Otomo", year: 1988, kind: "Film" },
    Transmission { fr: "Vous aider, c'est ma raison d'être.",
        vo: "Helping you is what I do.",
        title: "Moon", creator: "Duncan Jones", year: 2009, kind: "Film" },
    Transmission { fr: "Le travail est mystérieux et important.",
        vo: "The work is mysterious and important.",
        title: "Severance", creator: "Dan Erickson", year: 2022, kind: "Série" },
    Transmission { fr: "N'est-ce pas étrange de créer quelque chose qui vous déteste ?",
        vo: "Isn't it strange, to create something that hates you?",
        title: "Ex Machina", creator: "Alex Garland", year: 2014, kind: "Film" },
    Transmission { fr: "Il n'existe aucun gène pour l'esprit humain.",
        vo: "There is no gene for the human spirit.",
        title: "Bienvenue à Gattaca", creator: "Andrew Niccol", year: 1997, kind: "Film" },
    Transmission { fr: "Plus personne ne fait confiance à personne, et nous sommes tous très fatigués.",
        vo: "Nobody trusts anybody now, and we're all very tired.",
        title: "The Thing", creator: "John Carpenter", year: 1982, kind: "Film" },
    Transmission { fr: "Si ça saigne, on peut le tuer.",
        vo: "If it bleeds, we can kill it.",
        title: "Predator", creator: "John McTiernan", year: 1987, kind: "Film" },
    Transmission { fr: "Il n'y a ni bien ni mal. Il n'y a que l'opinion dominante.",
        vo: "There's no right, there's no wrong. There's only popular opinion.",
        title: "L'Armée des douze singes", creator: "Terry Gilliam", year: 1995, kind: "Film" },
    Transmission { fr: "Nous ne voulons pas conquérir l'espace. Nous voulons étendre la Terre à l'infini.",
        vo: "We don't want to conquer space. We want to expand Earth endlessly.",
        title: "Solaris", creator: "Andreï Tarkovski", year: 1972, kind: "Film" },
    Transmission { fr: "La violence est le dernier refuge de l'incompétence.",
        vo: "Violence is the last refuge of the incompetent.",
        title: "Fondation", creator: "David S. Goyer — d'après Isaac Asimov", year: 2021, kind: "Série" },
    Transmission { fr: "Bonjour chez vous.",
        vo: "Be seeing you.",
        title: "Le Prisonnier", creator: "Patrick McGoohan", year: 1967, kind: "Série" },
    Transmission { fr: "Fin de la transmission.",
        vo: "End of line.",
        title: "Tron", creator: "Steven Lisberger", year: 1982, kind: "Film" },
    Transmission { fr: "Bas les pattes, sale singe !",
        vo: "Take your stinking paws off me, you damned dirty ape!",
        title: "La Planète des singes", creator: "Franklin J. Schaffner", year: 1968, kind: "Film" },
    Transmission { fr: "Des routes ? Là où on va, on n'a pas besoin de routes.",
        vo: "Roads? Where we're going, we don't need roads.",
        title: "Retour vers le futur", creator: "Robert Zemeckis", year: 1985, kind: "Film" },
    Transmission { fr: "La vie trouve toujours un chemin.",
        vo: "Life finds a way.",
        title: "Jurassic Park", creator: "Steven Spielberg", year: 1993, kind: "Film" },
    Transmission { fr: "Salut, l'ami.",
        vo: "Hello, friend.",
        title: "Mr. Robot", creator: "Sam Esmail", year: 2015, kind: "Série" },
    Transmission { fr: "Au bout du compte, nous ne sommes que des histoires.",
        vo: "We're all stories in the end.",
        title: "Doctor Who", creator: "Sydney Newman", year: 1963, kind: "Série" },
    Transmission { fr: "Étrange, ce qui arrive à un monde privé de voix d'enfants.",
        vo: "Very odd, what happens in a world without children's voices.",
        title: "Les Fils de l'homme", creator: "Alfonso Cuarón", year: 2006, kind: "Film" },
];

/// GET /api/transmissions — la liste complète, dans l'ordre où le
/// client fera son propre tirage (il évite déjà la répétition en
/// mémorisant la dernière position vue).
pub async fn list() -> Json<&'static [Transmission]> {
    Json(ARCHIVE)
}
